title: Sistema de Asistencia
description: Módulo de asistencia diaria - MINERD
baseurl: "/asistenciaminerd" # cámbialo a "/nombre-del-repo" si publicas en https://usuario.github.io/nombre-del-repo
url: "https://jorge21028.github.io"

# IMPORTANTE: esta es la URL donde vive tu API PHP en Hostinger.
# Edítala con tu dominio real antes de publicar.
api_url: "https://institutoifgla.edu.do/asistencia-api"

plugins: []

exclude:
  - README.md
  - database/
  - Gemfile
  - Gemfile.lock
